# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
project './iosApp.xcodeproj'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/polyv_ef/plvspecs.git'
source 'https://github.com/volcengine/volcengine-specs.git'


target 'iosApp' do
# Comment the next line if you don't want to use dynamic frameworks
# use_frameworks! #:linkage => :static
use_frameworks!(:linkage => :static)
inhibit_all_warnings!
project_root = File.expand_path('..', __FILE__)
  # 保利威 多场景 SDK
#   pod 'PLVLiveScenesSDK', '1.29.0'
#   # 保利威 手机开播场景 需依赖的库
#   pod 'PLVBytedEffectSDK', '4.4.2'
#   pod 'PLVBeautyEffect','1.3.0'
  pod 'PLVBusinessSDK', '1.29.0', :subspecs => ['Beauty']
#   # 保利威 SM2加密 需依赖的库
#   pod 'PLVLOpenSSL', '~> 1.1.12100'
  pod 'PLVFoundationSDK', '1.29.0', :subspecs => ['CryptoUtils']
#   # 保利威 UI源码 需依赖的库
#   pod 'SDWebImage', '4.4.0'
#   pod 'MJRefresh', '~> 3.5.0'
#   pod 'SVGAPlayer', '~> 2.3'
#   pod 'Protobuf', '3.22.4'


pod 'polyv', :path => "#{project_root}/../submodule/ios/pod/polyv.podspec"

end

puts "首次执行前请先确认是否已执行此命令 brew install xcode-kotlin &xcode-kotlin install"
post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
if config.base_configuration_reference
 config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
 config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "13.0"
 config.build_settings['SWIFT_VERSION'] = "5.0"
end
end
end
end
