# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
project './iosApp.xcodeproj'

source 'https://cdn.cocoapods.org'
target 'polyv' do
# Comment the next line if you don't want to use dynamic frameworks
# use_frameworks! #:linkage => :static
use_frameworks! #(:linkage => :static)
inhibit_all_warnings!
project_root = File.expand_path('..', __FILE__)
pod 'polyv', :path => "#{project_root}/../polyv/ios/polyv.podspec"

end

puts "首次执行前请先确认是否已执行此命令 brew install xcode-kotlin &xcode-kotlin install"
post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
if config.base_configuration_reference
 config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
 config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "13.0"
 config.build_settings['SWIFT_VERSION'] = "5.0"
end
end
end
end
